using ControleDeMedicamentos.ConsoleApp.Compartilhado;

namespace ControleDeMedicamentos.ConsoleApp.ModuloRequisicaoDeSaida;

public interface IRepositorioRequisicaoDeSaida : IRepositorio<RequisicaoDeSaida>;